sudo: required
services:
  - docker

before_install:
  - docker build -t fabioadani/frontend -f Dockerfile.dev .

script:
  - docker run fabioadani/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-955501240318"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"